services:
  - type: web
    name: howismystock
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      flask db init
      flask db migrate -m "Initial migration"
      flask db upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: howismystock-db 
          property: connectionString